[package]
name = "worst"
version = "0.1.0"
authors = ["Drill Bear <vklquevs@gmail.com>"]
edition = "2018"

[lib]
name = "hell"
path = "src/mod.rs"

[[bin]]
name = "mworst"
path = "app/mworst.rs"

[dependencies]
downcast = "*"
num-traits = "*"
# num-rational = "*"
# rustyline = "*"
log = "*"
# simple_logger = "*"
# env_logger = "*"
# internship = { version = "*", default-features = false, features = [] }
objekt = "*"
# string_cache = "0.7" # alternative to internship

