[package]
name = "worst"
version = "0.1.0"
authors = ["Drill Bear <vklquevs@gmail.com>"]

[lib]
name = "hell"
path = "src/mod.rs"

[[bin]]
name = "hell"
path = "app/hell.rs"

[dependencies]
downcast = "0.9"
num-traits = "0.2"
num-rational = "0.2"
rustyline = "1.0"
log = "0.4"
env_logger = "0.5"

