[package]
name = "worst"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
genawaiter = "^0.99"
downcast-rs = "^1.2"
match-downcast = "^0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "^3", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0.2"

