#!/usr/bin/env sh
exec ./worst -s "$0" "$@"
!#

;;; vi: ft=scheme

; Worst CSound language

; TODO
; - run csound listening on a known port
; - make a connection by udp socket
; - write messages to it

define csound-send [
]

define midi-instrument [
]

abort

44100 sample-rate
2 channels
32 k-rate
1 db0

midi-instrument ; instr but midi-only

midi-note   ; <midi-note>
to-freq     ; cpsmidi => <freq>
midi-amp    ; ampmidi => <amp>

~sine       ; <freq> <amp> => <signal> or <amp> <freq> => <signal>

out         ; take one <signal>

:midi-demo  ; instrument at top: put it in a score and set it up


