#!/usr/bin/env sh
exec cargo run -- "$0" --worst-args "$0" "$@"
!#

[ 6 ]
list->definition
quote flop add-definition

flop

[ ; define
  quote quote uplevel ; name
  quote quote uplevel ; [def ...]
  list->definition
  1 dig
  quote add-definition uplevel
] list->definition quote define add-definition

define ' [quote quote uplevel]

define egg [7] ; ' [quote]

egg
describe drop

'test describe drop

; ok
[]
describe drop
"helo"
describe drop
[[5]]
describe drop
5 7 add describe drop

"wef\n" string->u8vector describe drop
"wef\n" string->u8vector standard-output-port 1 dig port-write

;;; vi: ft=scheme

